my_stringg = input(' mr.D - Как вам погода, сер ?                                            mr.B : ')
print('mr.B -', my_stringg,)
my_string = input('mr.D - И я так пологаю. А как вы считаете, что будет завтра ?            mr.B : ')
print('mr.B - ', my_string)
print('mr.D - А тут извольте не согласится !')
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ',''))
print(my_string[0])
print(my_string[-1])